name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_push_to_docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        uses: actions/checkout@v2
      - 
        name: read ubuntu version
        id: ubuntu_version
        uses: juliangruber/read-file-action@v1
        with:
          path: ./ubuntu_version
      - 
        name: read vscode version
        id: vscode_version
        uses: juliangruber/read-file-action@v1
        with:
          path: ./vscode_version
      -
        name: Build and push latest
        id: docker_build_latest
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          push: true
          tags: sefose/code-server:latest
          build-args: |
            UBUNTU_VERSION=${{ steps.ubuntu_version.outputs.content }}
            VSC_VERSION=${{ steps.vscode_version.outputs.content }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build_latest.outputs.digest }}
        
      - 
        name: add description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: sefose/code-server
          readme-filepath: ./README.md
      -
        name: Build and push version
        id: docker_build_version
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          push: true
          tags: sefose/code-server:${{ steps.ubuntu_version.outputs.content }}_${{ steps.vscode_version.outputs.content }}
          build-args: |
            UBUNTU_VERSION=${{ steps.ubuntu_version.outputs.content }}
            VSC_VERSION=${{ steps.vscode_version.outputs.content }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build_version.outputs.digest }}
